---
- name: SOS Report
  hosts: bastion_server
  remote_user: root
  gather_facts: false
  
  vars:
    ansible_ssh_pass: Admin12345
    node_name: compute1.ocp.olg.online.com
    case_id: 03586842

  roles:
   - role: must-gather
   - role: sos-report
   - role: addattachmant-upload
   - role: toolbox-upload


   