---
- name: SOS Report
  hosts: bastion_server
  remote_user: root
  gather_facts: false
  
  vars:
    ansible_ssh_pass: Admin12345
    node_names: 
     - compute1.ocp.olg.online.com
     - compute0.ocp.olg.online.com
    case_id: 03586842

  roles:
   - role: must-gather
   - role: sos-report
   - role: compress-attachmant
   - role: cleanup-namespaces

- name: upload attachments
  hosts: uploader
  remote_user: root
  gather_facts: false

  vars:
    ansible_ssh_pass: Admin12345
    case_id: 03586842

  roles:
   - role: toolbox-upload
