---
- name: Double loop
  hosts: node
  remote_user: osboxes
  gather_facts: true

  vars:
   key1: [1, 2, 3]
   key2: [7, 8, 9]

  tasks: 
  - name: Permutation
    ansible.builtin.debug:
     msg: "{{ item[0] }} - {{ item[1] }} - {{ ansible_loop.index0 }}"
    loop: "{{ key1 | product(key2) | list }}"
    loop_control:
     extended: true

