---
- name: for practice 
  hosts: node
  remote_user: osboxes
  gather_facts: false

  vars:
   key1: [1,2,3,4,5,6,7,8,9,10]

  tasks:
   - name: print bigger than six
     ansible.builtin.template:
      src: for.j2
      dest: /tmp/for
     