- name: Run toolbox command
  ansible.builtin.command: 
   toolbox 'rm -f /etc/redhat-support-tool.conf; cp /host/tmp/redhat-support-tool.conf /etc/redhat-support-tool.conf; redhat-support-tool addattachment -c {{ case_id }} /host/tmp/diagnostic-data.tar.gz'
   